=== christoph-hesse/question-under-discussion/corpus/qud2.dtd
<!--
    1. Root may contain one QUD (Q0)
    2. QUDs may contain e.g. focus and topic tags  and sub-QUDs
       QUDs have a string attribute containing the formulated question
    3. focus tags, topic tags etc. contain segments of plain text (corpus data), which correspond to
        the content of brackets of e.g. a topic or focus     
-->

<!ELEMENT ROOT (QUD)>
<!ELEMENT QUD ((DT|AT|CT|F|CMT|CON|QUD)+)>
<!ATTLIST QUD string CDATA #REQUIRED>
<!ELEMENT DT (CT|F|CMT|CON)+>
<!ELEMENT AT (CT|F|CMT|CON)+>
<!ELEMENT CT ((SEGMENT+)|(NAI*, SEGMENT+)|(SEGMENT+, NAI*))+>
<!ELEMENT F ((SEGMENT+)|(NAI*, SEGMENT+)|(SEGMENT+, NAI*))+>
<!ELEMENT CMT ((SEGMENT+)|(NAI*, SEGMENT+)|(SEGMENT+, NAI*))+>
<!ELEMENT CON ((SEGMENT+)|(NAI*, SEGMENT+)|(SEGMENT+, NAI*))+>
<!ELEMENT NAI (SEGMENT)>
<!ELEMENT RES (#PCDATA)>
<!ELEMENT SEGMENT (#PCDATA)>


<!--
    discourse topic:    DT (Discourse Topic)             Diskursthema
    sentence topic:     AT (Assertion Topic)             Satzthema
    contrastive topic:  CT (Contrastive Topic)            jetzt noch keine tiefen Gedanken
    background:         CON (Context = Alte Infos)            gegeben in der QUD
    focus:              F (Focus)              Antwort auf Frage
    comment:            CMT (Comment = Neue Info)
    non-at-issue:       NAI
    >
    SEGMENTS, die nicht in <NAI> embedded sind, sind at-issue
<!Mann und Thompson List of RST relations>

=== christoph-hesse/question-under-discussion/corpus/Skoda_Superb.xml
<?xml version="1.0"?>
<!DOCTYPE ROOT SYSTEM "qud2.dtd">
<!--Skoda Superb-->	

<ROOT>
<QUD string="Was ist mit dem Fahrbericht des Skoda Superb?">
<!--DT = Introduction-->    
    <QUD string="Was ist mit dem Superb?">
        <CON>
            <SEGMENT>Der</SEGMENT>
            <NAI><SEGMENT>große</SEGMENT></NAI>
            <SEGMENT>Superb</SEGMENT>
        </CON>
        <F>
            <SEGMENT>wird überarbeitet</SEGMENT>
            <SEGMENT>und</SEGMENT>
            <SEGMENT>kommt als Plug-in-Hybrid.</SEGMENT>
        </F>

        <QUD string="Was gibt es zu Elektroautos zu sagen?">
            <AT>
                <SEGMENT>Der</SEGMENT>
                <NAI><SEGMENT>kleine</SEGMENT></NAI>
                <SEGMENT>Citigo</SEGMENT>
                <SEGMENT>fährt nur noch elektrisch.</SEGMENT>
            </AT>
            <F>
                <SEGMENT>Alle werden elektrisch,</SEGMENT>
                <SEGMENT>auch Škoda,</SEGMENT>
            </F>
            <CMT>
                <SEGMENT>die VW-Tochterfirma aus Tschechien.</SEGMENT>
            </CMT>    

            <QUD string="Welche Änderungen am Superb gibt es?">
                <AT>
                    <SEGMENT>Anlässlich</SEGMENT>
                </AT>
                <CON>
                    <SEGMENT>einer Überarbeitung</SEGMENT>
                    <SEGMENT>des</SEGMENT>
                </CON>
                <CMT>
                    <SEGMENT>Flaggschiffs</SEGMENT>
                </CMT>    
                <CON>    
                    <SEGMENT>Superb</SEGMENT>
                </CON>
                <F>
                    <SEGMENT>wird die Gelegenheit genutzt,</SEGMENT>
                    <SEGMENT>dem großen Škoda auch eine Version mit Plug-in-Hybrid zu spendieren.</SEGMENT>
                </F>

                <QUD string="Was ist mit einer Plug-in-Hybrid Version?">
                    <AT>
                        <SEGMENT>Zudem</SEGMENT>
                    </AT>
                    <F>
                        <SEGMENT>wird es</SEGMENT>
                        <SEGMENT>erstmals</SEGMENT>
                        <SEGMENT>eine robuste Scout-Version vom Superb geben.</SEGMENT>
                    </F>
                </QUD>
            </QUD>        
            <!--DT = Launch-->
            <QUD string="Wie werde Elektroautos (bei Skoda) produziert?">
                <AT>
                    <SEGMENT>Auch</SEGMENT>
                </AT>
                <CON>
                    <SEGMENT>Škoda rechnet damit,</SEGMENT>
                </CON>
                <F id="1">
                    <SEGMENT>dass</SEGMENT>
                    <SEGMENT>bis zum Jahr 2025 rund ein Viertel der Produktion auf Elektromodelle entfallen wird,</SEGMENT>
                    <SEGMENT>Plug-in-Hybride mitgerechnet.</SEGMENT>
                </F>
                <RES><SEGMENT>Allerdings</SEGMENT></RES>
                <AT><SEGMENT>muss noch</SEGMENT></AT>
                <F id="2"><SEGMENT>bis Anfang 2020 auf den Superb mit Stecker gewartet werden,</SEGMENT></F>
                <RES><SEGMENT>während </SEGMENT></RES>
                <F id="3"><SEGMENT>die Marktpremiere des aufgefrischten Superb</SEGMENT></F>
                <RES><SEGMENT>und</SEGMENT></RES>
                <F id="3"><SEGMENT>des Superb Scout schon Ende Juni ist.</SEGMENT></F>
            </QUD>
        </QUD>
        <!--DT = Price-->  
        <QUD string="Was kostet der Skoda Superb?">
            <CON>
                <SEGMENT>Die genauen Preise</SEGMENT>
            </CON>
            <F>
                <SEGMENT>verschweigt Škoda noch,</SEGMENT>
                <SEGMENT>sie sollen jedoch auf dem Niveau des Vorgängers liegen.</SEGMENT>
            </F>
            <DT>
                <SEGMENT>Der Plug-in-Hybrid</SEGMENT>
            </DT>
            <F>
                <SEGMENT>soll preislich nur leicht über den Dieselmodellen angesiedelt sein.</SEGMENT>
            </F>
        </QUD>
        <!--DT = Design--> 
        <QUD string="Wieviel Platz bietet der Superb?">

            <QUD string="Was ist mit dem Sedan und dem Kombi?">
                <CON>
                    <SEGMENT>Limousine und Kombi</SEGMENT>
                </CON>
                <F>
                    <SEGMENT>haben fortan einen flacheren und breiteren Kühlergrill</SEGMENT>
                    <SEGMENT>und</SEGMENT>
                    <SEGMENT>sehen etwas dynamischer als bisher aus.</SEGMENT>
                </F>
            </QUD>

            <QUD string="Wie sind die Abmessungen?">
                <CON>
                    <SEGMENT>Die Abmessungen</SEGMENT>
                </CON>
                <F>
                    <SEGMENT>sind fast identisch zum Vorgänger.</SEGMENT>
                </F>

                <QUD string="Wie sind die Abmessungen des Sedan?">

                    <QUD string="Warum haben sich die Abmessungen des Sedan geändert?">
                        <F>
                            <SEGMENT>Bedingt durch die neue Frontschürze,</SEGMENT>
                        </F>
                    </QUD>

                    <F>
                        <SEGMENT>ist die Limousine jetzt 4,87 Meter lang,</SEGMENT>
                    </F>
                </QUD>

                <QUD string="Wie sind die Abmessungen des Kombis?">
                    <CON>
                        <SEGMENT>der Kombi</SEGMENT>
                    </CON>
                    <F>
                        <SEGMENT>misst 4,86 Meter.</SEGMENT>
                    </F>
                </QUD>
            </QUD>
        </QUD>

        <QUD string="Welche Innovationen gibt es?">
            <CON>
                <SEGMENT>Innovationen</SEGMENT>
            </CON>
            <F>
                <SEGMENT>stecken vor allem unterm Blech.</SEGMENT>
            </F>

            <QUD string="Was ist mit den Voll-LED-Matrix-Scheinwerfer?">
                <F>
                    <SEGMENT>Erstmals</SEGMENT>
                    <SEGMENT>kommen</SEGMENT>
                </F>
                <CON>
                    <SEGMENT>Voll-LED-Matrix-Scheinwerfer</SEGMENT>
                </CON>
                <F>
                    <SEGMENT>in einem Škoda zum Einsatz,</SEGMENT>
                </F>
            </QUD>

            <AT>
                <SEGMENT>außerdem</SEGMENT>
            </AT>
            <F>
                <SEGMENT>halten</SEGMENT>
                <SEGMENT>neue Assistenzsysteme</SEGMENT>
            </F>

            <QUD string="Was ist mit Assistanzsystemen?">
                <AT>
                    <SEGMENT>wie beispielsweise</SEGMENT>
                </AT>
                <F>
                    <SEGMENT>der vorausschauende adaptive Abstandsregler</SEGMENT>
                    <SEGMENT>und</SEGMENT>
                    <SEGMENT>der Side Assist Einzug in den Superb.</SEGMENT>
                </F>
            </QUD>

            <QUD string="Welche Kraftquelle hat der Skoda Superb?">
                <CON>
                    <SEGMENT>Als Kraftquelle</SEGMENT>
                </CON>
                <F>
                    <SEGMENT>stehen zunächst drei Ottotriebwerke mit 150 bis 272 PS</SEGMENT>
                    <SEGMENT>und</SEGMENT>
                    <SEGMENT>drei Dieselaggregate mit 120 bis 190 PS zur Wahl.</SEGMENT>
                </F>
            </QUD>

            <QUD string="Was bietet die Scout Variante mit dezenter Plastik-Beplankung?">
                <CON>
                    <SEGMENT>Die Scout-Variante mit dezenter Plastik-Beplankung,</SEGMENT>
                </CON>
                <AT>
                    <SEGMENT>die nur als Kombi und mit serienmäßigem Allradantrieb daherkommt,</SEGMENT>
                </AT>
                <F>
                    <SEGMENT>ist 1,5 Zentimeter höhergelegt,</SEGMENT>
                </F>
                <F>
                    <SEGMENT>hier</SEGMENT>
                    <SEGMENT>stehen</SEGMENT>
                    <SEGMENT>die beiden Zweiliter-Topmotorisierungen</SEGMENT>
                    <SEGMENT>(TSI mit 272 PS und TDI mit 190 PS)</SEGMENT>
                    <SEGMENT>parat.</SEGMENT>
                </F>
            </QUD>

            <QUD string="Was erwartet Skoda (die Firma)?">
                <CON>
                    <SEGMENT>Škoda Deutschland erwartet,</SEGMENT>
                </CON>
                <F>
                    <SEGMENT>dass sich rund zehn Prozent aller Superb-Käufer für den Scout entscheiden werden.</SEGMENT>
                </F>
            </QUD>

            <QUD string="Was ist die wichtigste Innovation?">
                <CON>
                    <SEGMENT>Wichtigste Neuerung</SEGMENT>
                    <SEGMENT>ist</SEGMENT>
                    <SEGMENT>freilich</SEGMENT>
                </CON>
                <F>
                    <SEGMENT>das Plug-in-Modell,</SEGMENT>
                    <SEGMENT>das das Kürzel iV trägt.</SEGMENT>
                </F>
            </QUD>
        </QUD>

        <QUD string="Welche Versionen gibt es?">
            <CON>
                <SEGMENT>Es</SEGMENT>
                <SEGMENT>ist</SEGMENT>
            </CON>
            <F>
                <SEGMENT>als</SEGMENT>
                <SEGMENT>Limousine oder Kombi</SEGMENT>
                <SEGMENT>erhältlich.</SEGMENT>
            </F>

            <QUD string="Was ist mit Hybrid-Antrieb?">
                
                <QUD string="Was ist mit dem Plug-in-Hybrid?">
                    <CON>
                        <SEGMENT>Der Plug-in-Hybrid</SEGMENT>
                    </CON>
                    <F>
                        <SEGMENT>kombiniert</SEGMENT>
                        <SEGMENT>einen 1,4-Liter-TSI-Benziner mit 156 PS</SEGMENT>
                        <SEGMENT>und</SEGMENT>
                        <SEGMENT>einen 116 PS starken Elektromotor.</SEGMENT>
                    </F>
    
                    <QUD string="Was ist mit der Kraft?">
